version: "3.9"
services:
  caddy:
    image: ghcr.io/pratyay360/caddy-cloudflare-sqllite:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
      - "2019:2019"
    environment:
      - CLOUDFLARE_API_TOKEN=${env.CLOUDFLARE_API_TOKEN}
    volumes:
      - ./caddy.json:/etc/caddy/caddy.json:Z
      - ./caddy_data:/data:Z
      - ./caddy_config:/config:Z
      - ./routes.db:/etc/caddy/routes.db:Z
    command: ["caddy", "run", "--config", "/etc/caddy/caddy.json"]
    networks: 
      -  mdebzoti
networks:
    mdebzoti:
       driver: bridge
       expose: true